### ISSUE TITLE
Failing test due to module dependency issue

### ISSUE THREAD

**Issue by jamesobutler** [simonoxen/SlicerANTs#2]
Failing test on CDash https://slicer.cdash.org/test/18100882. Full testing dashboard can be seen [here](https://slicer.cdash.org/index.php?project=SlicerPreview&date=2021-06-18&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SlicerAnts).

Here you are creating a widget representation of a Slicer CLI module that you are putting in your Slicer ScriptedLoadableModule. However you are not listing antsCommand as a module dependency of antsRegistration.

https://github.com/simonoxen/SlicerANTs/blob/24ede7611e4574785314d6420bfd51ceeef9b340/antsRegistration/antsRegistration.py#L81
https://github.com/simonoxen/SlicerANTs/blob/24ede7611e4574785314d6420bfd51ceeef9b340/antsRegistration/antsRegistration.py#L27

**Comment by simonoxen** [comment]
Thanks! added the dependency here a8b3251

**Comment by jamesobutler** [comment]
The test that doesn’t have a Slicer main window is not passing. See https://slicer.cdash.org/test/18118093

**Comment by simonoxen** [comment]
Thanks again. Although I don't quite understand what causes the issue. The error is the following:

> When loading module  "antsRegistration" , the dependency "antsCommand" failed to be loaded.

Should I change the order in CMake?

https://github.com/simonoxen/SlicerANTs/blob/master/CMakeLists.txt#L37-L39
